import = [
    "~/.config/alacritty/colors.toml",
    "~/.config/alacritty/keybindings.toml",
    "~/.config/alacritty/font.toml",
]

[env]
TERM = "xterm-256color"

[window]
opacity = 1
title = "Alacritty"

[window.padding]
x = 5
y = 5
